# Generated by Django 4.1.5 on 2023-01-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
