# Generated by Django 4.1.5 on 2023-01-14 08:26

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=home.models.Product.get_file_name)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='productsbrand',
            options={'ordering': ('position', 'name')},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'ordering': ('position', 'name')},
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productsbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productscategory'),
        ),
    ]
