# Generated by Django 4.1.5 on 2023-01-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_alter_productsbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('rating', 'category', 'brand', 'name')},
        ),
    ]
